common/Makefile.common.mk
Fix:
```
make: *** No rule to make target 'config-docker', needed by 'build-push-images'.  Stop.
```
=> add config-docker target.

deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
Refactor the operandBindInfo `bindings`
The `bindings` in the `OperandBindInfo` and `OperandRequest` is not actually a list, it only includes a `public` scope and a `private ` scope.  Could we use a dual object to replace the list? 
For example,
Change
```
"spec": {
"operand": "ibm-licensing-operator",
"registry": "common-service",
"description": "Binding information that should be accessible to licensing adopters",
"bindings": [
{
"scope": "public",
"secret": "ibm-licensing-token"
}
]
}
```
to
```
"spec": {
"operand": "ibm-licensing-operator",
"registry": "common-service",
"description": "Binding information that should be accessible to licensing adopters",
"bindings": {
"public": {
"secret": "ibm-licensing-token",
"comfigmap": "ibm-licensing-cm"
},
"private": {
"secret": …
```
=> Update bindings structure

deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
- to merge this PR add comment: `/lgtm`
- after merging clone this repository from master branch
- then in root directory "ibm-licensing-operator" run this command:
```bash
./common/scripts/push-csv.sh
```
- it will prompt for your quay username, then password and then version, for version type: 1.1.3
- after push is done you can verify if after Catalog Source refresh on your cluster stable will point to 1.1.3 (uninstall ibm licensing operator, delete Catalog Source opencloud-operators, wait few minutes, install ibm licensing operator from stable-v1 channel)
=> update stable to 1.1.3

deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml, deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicensings_crd.yaml, pkg/apis/operator/v1alpha1/ibmlicensing_types.go, pkg/controller/ibmlicensing/ibmlicensing_controller.go, pkg/resources/containers.go, pkg/resources/secrets.go
- make hub token to be taken from secret instead string
- fix problem with empty cluster name in operand
- fix info log for watcher which did not say what resources are being watched
- change CRD naming of parameters from `hub` to `reporter`
=> Fix sender parameters

deploy/crds/operator.ibm.com_ibmlicenseservicereporters_crd.yaml, deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml, deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicenseservicereporters_crd.yaml, deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicensings_crd.yaml, pkg/apis/operator/v1alpha1/helper.go, pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go, pkg/controller/ibmlicensing/ibmlicensing_controller.go, pkg/resources/helper.go, pkg/resources/reporter/secrets.go, pkg/resources/service/secrets.go
- change math rand to crypto rand for security
- fix problem with CRD for LS Reporter having no way to change name of api secret token, now it can be set in CR with any value not only ibm-licensing-token
=> Change rand function for security and fix Reporter CRD potential problem

deploy/olm-catalog/ibm-licensing-operator/1.2.2/ibm-licensing-operator.v1.2.2.clusterserviceversion.yaml, pkg/apis/operator/v1alpha1/helper.go, pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
- update ui digest to 1.2.2
- changed delay after resource creation in reporter controller from minute to 5 second as it only happens when resource doesn't exist and has been succesfuly created and with minute added previously it would make client wait too long for all resources to be created
=> update ui digest with update to 1.2.2

.github/workflows/kind.yml, .github/workflows/ocp.yml, controllers/ibmlicensing_controller_test.go
now all our test will be run on each k8s which we support
it means that it will be check also all OCP 
4.4, 4.5, 4.6, 4.7
If there will be any problems related to API versions in k8s this test should find it
=> run test on varius k8s

Makefile
During creating CatalogSource Image (based on new catalog format bundle format) we got from opm the message:
```replaces nonexistent bundle ibm-licensing-operator.v1.4.1```
```
time="2021-03-25T11:37:42Z" level=info msg="loading bundle file" dir=bundle_tmp021324230/manifests file=operator.ibm.com_ibmlicensings.yaml load=bundle
time="2021-03-25T11:37:42Z" level=warning msg="permissive mode enabled" bundles="[hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/ibm-licensing-operator-bundle:1.5.0]" error="Invalid bundle ibm-licensing-operator.v1.5.0, replaces nonexistent bundle ibm-licensing-operator.v1.4.1"
time="2021-03-25T11:37:42Z" level=info msg="Generating dockerfile" bundles="[hyc-cloud-private-scratch-docker-local.artifactory.swg-devops.com/ibmcom/ibm-licensing-op …
```
=> CatalogSource image generation during multiarch task

controllers/resources/service/meter_definition.go
Because of CP4D with the same productID
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45974
=> update meterdef for bundle

bundle/manifests/ibm-license-service_rbac.authorization.k8s.io_v1_clusterrole.yaml, config/rbac/role_operands.yaml
probably skip during migration to bundle format
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46109
=> fix for usage container lack of rbac

README.md, docs/Content/Install_from_scratch.md, docs/Content/Install_offline.md, docs/Content/Install_on_OCP.md, docs/Content/Install_without_OLM.md, docs/Content/Preparing_for_installation.md, docs/Content/Retrieving_data.md, docs/Content/Troubleshooting.md, docs/License_Service_main.md
The following updates are made:
IBM Cloud Platform Common Services -> IBM Cloud Pak foundational services
IBM Knowledge Center -> IBM Documentation
old KC links -> IBM Documentation links
Additionally:
the value of operator_release_version changed to v1.5.0 now
other variables updated to point to 1.5.0
a mote added to readme to call out that master branch contains development content and should not be used
=> doc updates

controllers/resources/deployments.go
Usage of reflect.DeepEqual to check equality of
corev1.EnvVar arrays may result in false negatives,
which leads to a infinite loop of recreating pods, trying to match container's env vars with ones
from LSR spec envVariable.
=> fixed env vars comparison for containers

README.md, docs/Content/Install_from_scratch.md, docs/Content/Install_offline.md, docs/Content/Install_without_OLM.md, docs/Content/Installation_scenarios.md, docs/Content/Preparing_for_installation.md, docs/License_Service_main.md
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50573
@SzymonKowalczyk
Versions changes to 1.10 and hyperthreading added.
Questions:
Do we need to list all operator versions in readme.md? Are all these versions supported?
I put hyperthreading in preparing to install topic. Is that a good fit? Or would it be better under configuration?
=> update documentation for 1.10

README.md
@SzymonKowalczyk 
Hi Szymon, this branch has the old doc version - contained in readme. I added the following note at the top to indicate that this documentation is outdated: 
**IMPORTANT:** The current branch contains the operator and documentation for License Service version 1.1.x. Switch to another branch to view the content for other releases. This documentation is outdated. To view the documentation for the latest version of License Service, see [License Service for stand-alone IBM Containerized Software](https://ibm.biz/license_service4containers).**
Please review, tahnks!
=> update note about outdated documentation

README.md
@SzymonKowalczyk 
Hi Szymon, this branch has the old doc version - contained in readme. I added the following note at the top to indicate that this documentation is outdated: 
**IMPORTANT:** The current branch contains the operator and documentation for License Service version 1.1.x. Switch to another branch to view the content for other releases. This documentation is outdated. To view the documentation for the latest version of License Service, see [License Service for stand-alone IBM Containerized Software](https://ibm.biz/license_service4containers).**
Please review, thanks!
=> add note about outdated documentation

controllers/resources/reporter/routing.go
Increased timeout on License Service Reporter route addresses error where it was impossible to download very large snapshots (eg. 36 datasources for previous 2 years)
=> Increase LSR route timeout to 90s

controllers/ibmlicenseservicereporter_controller.go, controllers/resources/reporter/helper.go, controllers/resources/reporter/routing.go, controllers/resources/reporter/volumes.go
* switch default route to reencrypt
* provide external certificate to a route
* add self-sign cert generation and rotation
* generate certificate specifically for route host
* add ownership reference to secret, cleanup code, handle more edgecases
* dummy change
* Fix linter
* linter fix
* fix fips not possible to update tls in route
* fix fips not having custom host role
* fips route reconcile decrease cooldown to 10s
* Fix population of route with custom certificate
* Fix logic error in CompareRoutes function
* Fix handling of certificate volumes in LS pod
* Fix logic error in CompareRoutes function
* change certificate validity period to 1 year
* Fixed typo in the output log
* move parsing certificate to common code
* Check external certificate hostname
* FIPS logic for self-signed …
=> Fips compliance lsr (#696)

controllers/operandrequest_discovery.go
Fix error when there are duplicated namespaces added to OperatorGroup in case of two (or more) OperandRequests discovered in the same namespace.
=> do not add redundant namespaces to operatorgroup

controllers/ibmlicensing_controller.go
Fix certificate secrets not generating when ingress is enabled (non ocp envs).
internal
=> Enable certificate generation when ingress is enabled

.github/workflows/kind.yml, .gitignore, controllers/ibmlicensing_controller_test.go
Make github action workflow fails if make unit-test exits with error code 1.
```
FAIL	github.com/IBM/ibm-licensing-operator/controllers	600.041s
FAIL
make: *** [Makefile:330: unit-test] Error 1
```
Even though the make exits with error, the workflow is successful, it should also fail.
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/<issue number>
=> capture the error from make unit-test

.github/workflows/kind.yml, .gitignore
Make github action workflow fails if make unit-test exits with error code 1.
```
FAIL	github.com/IBM/ibm-licensing-operator/controllers	600.041s
FAIL
make: *** [Makefile:330: unit-test] Error 1
```
Even though the make exits with error, the workflow is successful, it should also fail.
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/<issue number>
=> Add checking exit code check in pipeline

api/v1alpha1/helper.go
Rename secret holding token used to upload data to the IBM License Service Reporter (in line with changes with IBM License Service Reporter Operator).
=> rename lsr token secret

controllers/ibmlicensing_controller_test.go
Fix kind test failing because of the 404 error when executing k8s.get() on non-existing resource. Check if resource exist in the loop instead of failing.
NaN
-
-
=> Add check for the nil Spec - avoid nullpointer

controllers/resources/deployments.go, controllers/resources/deployments_test.go, testutils/mocks.go
Fix operator not reconciling change of the Reporter upload token secret name, used by the License Service.
=> fix operator not reconciling reporter upload token secret name for LS

controllers/resources/service/meter_definition.go
The associated change in the LicSvc operand is https://github.ibm.com/cloud-license-reporter/cloud-reporter/pull/531 - i.e. the Services breakdown is no longer represented as an adoption metric, but a license metric breakdown.
The resulting `MeterDefintion` shall look like:
```yaml
spec:
group: '{{ .Label.productId}}.licensing.ibm.com'
kind: IBMLicensing-Service
meters:
- period: 24h0m0s
aggregation: max
query: 'avg_over_time(cp4d_capability{}[1d])'
name: Cp4d Capability
metricId: '{{ .Label.parentMetricId}}'
valueLabelOverride: '{{ .Label.value}}'
workloadType: Service
dateLabelOverride: '{{ .Label.date}}'
groupBy:
- metricId
- productId
- parentMetricId
- parentProductId
- topLevelProductId
- topLevelMetricId
```
=> Update Meter Definition to expose Services breakdown, including the new top-level product id

api/v1alpha1/ibmlicensing_types.go, bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml, bundle/manifests/operator.ibm.com_ibmlicensings.yaml, config/crd/bases/operator.ibm.com_ibmlicensings.yaml, controllers/ibmlicensing_controller.go, controllers/resources/deployments.go, controllers/resources/helper.go, controllers/resources/service/helper.go, controllers/resources/service/secrets.go, controllers/resources/service/service_monitor.go, controllers/resources/service/services.go
Code tested on a default IBMLicensing operand provisioning. No extra params or testing was done yet (e.g. no testing with ingress enabled). To my knowledge, all resources owned by the operand should be affected when applying `spec.labels`.
Functionalities provide an easy extension for adding `spec.annotations`.
=> Add spec labels support

bundle.Dockerfile, common/scripts/catalog/Dockerfile, common/scripts/catalog_build.sh
When executing a Docker image, by default the user that runs the process is root. As a best practice, you should run with a user that does not have high privileges; this help prevent privilege escalation. Apple the Principle of Least Privilege (POLP) when building or running a Docker image: give your user only the privileges it needs to perform the intended functions.
By default, Docker runs containers with a root user, which can create a security risk and cause permission issues when accessing files and directories. Hence, the container user should be a non-root user with appropriate permissions.
Just as in classic VM deployments, processes should not be run with root permissions. Instead, the image should contain a non-root user that runs the application.
In a Dockerfile, you can …
=> Add USER instruction to the dockerfiles to enhance security

bundle/manifests/ibm-license-service-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml, bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml, common/Makefile.common.mk, config/rbac/role_binding.yaml
Add missing `ClusterRoleBinding` for the `cluster-monitorg-view` `ClusterRole` required for Wazi on OCP 4.15+
=> [LTSR] Fix bug 63327

controllers/resources/deployments.go, controllers/resources/service/deployments.go
**Context**
Currently it is possible to pass `imagePullSecrets` for the LS deployment to the CR, however the deployment will not be reconciled on this change. The values will only be applied during the deployment recreation.
**Solution**
Detect `imagePullSecrets` changes in the CR and reconcile LS deployment.
**Expected behaviour**
- if `imagePullSecrets` is **not** provided in the CR, then in the LS pod the field will be empty or it will be populated automatically with `imagePullSecrets` from `ServiceAccount` (if present)
- if `imagePullSecrets`  provided in the CR, then in the LS pod, this value will be used, overriding possible `imagePullSecrets` set by `ServiceAccount` (if present)
Issue: 62826
=> [LTSR] Reconcile on imagePullSecrets change in IBMLicensing CR

.github/workflows/kind.yml
One of our action (upload-artifact@v2) was deprecated and failed automatically. Previously I introduced upload-artifact@v4 to fix builds however it has breaking changes - e.g. you can't upload artifacts with same name (as we do). Now I add K8s version to name so they have different names.
[My kindness <3 <3 ](https://jsw.ibm.com/browse/ILS-132)
-
-
=> change name of artifact

controllers/operandrequest_discovery.go
**Split from issue**: https://github.ibm.com/PrivateCloud-analytics/CPD-Quality/issues/30974
**JIRA**: https://jsw.ibm.com/browse/ILS-233
**Bug:**
The LS operator keeps adding and removing namespace from OperatorGroup, which causes it to restart constantly.
**Why it happens:**
The issue persists because there is an OperandRequest in a non-existent namespace. Our OperandRequestController detects the OperandRequest and add its namespace to the OperatorGroup. We also have an async job which periodically runs and checks whether namespaces inside OperatorGroup exist (introduced here: https://github.com/IBM/ibm-licensing-operator/pull/932). The namespace is not present in the cluster, so we delete it from OperatorGroup, which triggers LS operator restart. The reason why there is an …
=> ILS-233 LS operator keeps restarting when there is OperandRequest in non-existent namespace

.github/workflows/ci.yml, common/config/.golangci.yml, controllers/ibmlicensing_controller.go
Added flag -buildvcs=false that disables version control information embedding during the build process and unblocks the golangci lint error:
```log
VCS status: exit status 128
```
Setting -buildvcs=false tells the Go tool to skip embedding any version control information in the binary.
This allows to run linter in a clean or isolated environment without access to the version control system.
Docs:
```
-buildvcs
Whether to stamp binaries with version control information. By default,
version control information is stamped into a binary if the main package
and the main module containing it are in the repository containing the
current directory (if there is a repository). Use -buildvcs=false to
omit version control information.
```
More info: https://go.dev/doc/go1.18#go-version
=> ILS-306 Update check-tool runner to node 20
