IBM/ibm-licensing-operator

- build/Dockerfile
fix possible vulnerability in old image base
> update Dockerfile base image

- README.md
- common/scripts/ibm_licensing_operator_install.sh
fix script for icp, add example ingress in readme for icp and ibm cloud
> Fix automatic script for icp

- README.md
Hi, This is a new version of our readme that follows the standard readme template for all IBM operators. I have done minor changes based on feedback from Piotr Godowski. Once this is merged to master, the link to automatic installation will change - please inform Andrzej Pietrzak about this change.
> Bk new readme template

- deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
@adamdyszy I create this pr for creating the beta channel for the 3.4 release. I will push the operator bundle from this PR to the quay.io for the SERT team can test asap.
Please correct me if I made anything wrong in this PR, thanks.
> Use digest to replace tag and Create beta channel

- deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
- deploy/olm-catalog/ibm-licensing-operator/1.1.1/operator.ibm.com_ibmlicensings_crd.yaml
- pkg/apis/operator/v1alpha1/ibmlicensing_types.go
> fix 1.1.1 CRD to not force version parameter that breaks backward

- Makefile
- README.md
- build/Dockerfile
- deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
- deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicensings_crd.yaml
- deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
- deploy/operator.yaml
- pkg/apis/operator/v1alpha1/helper.go
- pkg/apis/operator/v1alpha1/ibmlicensing_types.go
- pkg/resources/containers.go
- version/version.go
- update readme to included latest release information
- update dev channel to 1.2.0
- update security image in Dockerfile
> Update to 1.2.0

- README.md
- deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
- deploy/operator.yaml
> memory limit to 100MB

- build/Dockerfile
- pkg/controller/ibmlicensing/ibmlicensing_controller.go
- pkg/resources/secrets.go
also updated image in Dockerfile for security and fixed some update logic
> Controller update for configmap

- pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
- pkg/controller/ibmlicensing/ibmlicensing_controller.go
- pkg/resources/deployments.go
make updating check all containers, init containers, and their probes instead only first container
> fix deployment reconcilation

- pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
- pkg/controller/ibmlicensing/ibmlicensing_controller.go
- pkg/resources/helper.go
- pkg/resources/reporter/services.go
- pkg/resources/service/containers.go
- pkg/resources/service/services.go
before merge please download it and again recheck
the issue was related with setting certSource to OCP always on openshift
> fix issue related with http and ocp

- pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
- pkg/controller/ibmlicensing/ibmlicensing_controller.go
fix race condition for get after create with sleep, fix logging for that issue as it is not error
> race condition log error fix

- .github/workflows/ocp.yml
> turn off ibmcloud

- common/scripts/ibm_licensing_operator_install.sh
- add channel option [-l | --channel] (could not use -c cause -c was already used for different option)
- try install olm if OLM CRD exists but OLM CSV don't, fixing problem for IKS
- show token and route url at the end, add option to not show token [-n | --no-secret-output]
> Add some features to automatic script

- docs/Content/Install_offline.md
- docs/Content/Install_without_OLM.md
- docs/Content/Installation_scenarios.md
- docs/Content/Preparing_for_installation.md
- docs/License_Service_main.md
> Bk installationwithout olm

- docs/Content/Install_offline.md
- docs/Content/Install_without_OLM.md
Recent documentation updates based on post-testing feedback.
> Recent updates

- deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/apis/operator/v1alpha1/helper.go
> Update ui operand digest

- .github/workflows/kind.yml
- Makefile
- common/scripts/codecov.sh
- controllers/ibmlicensing_controller_test.go
- controllers/suite_test.go
- go.mod
- go.sum
The first implementation of unit tests for our operator
> unitest based on ginkgo, gomega and testEnv

- deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
- deploy/role.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/43664
> add sa for meterdefinition

- .github/workflows/kind.yml
- .github/workflows/ocp.yml
- Makefile
- controllers/ibmlicensing_controller_test.go
- controllers/suite_test.go
add more unit tests
we need to check if we run it on ocp or on k8s
we need to decide where to run code-coverage on ocp or on k8s
> Aobrzut units

- controllers/resources/service/service_monitor.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44568
not merge yet 
working in progress
> fix servis monitor

- api/v1alpha1/helper.go
- controllers/ibmlicensing_controller_test.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44949
> RHMP and chargeback

- bundle/metadata/annotations.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45637
> package name fix

- Makefile
https://docs.openshift.com/container-platform/4.6/operators/admin/olm-managing-custom-catalogs.html
> multiarch fix for catalogsource

- docs/Content/Install_offline.md
CHanged the order of steps in the offline installation procedure. Cloning the repo is the first step.
> move cloning the repository to the beginning

- api/v1alpha1/ibmlicenseservicereporter_types.go
- api/v1alpha1/ibmlicensing_types.go
- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
- bundle/manifests/operator.ibm.com_ibmlicensings.yaml
- config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
- config/crd/bases/operator.ibm.com_ibmlicensings.yaml
- config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
- controllers/resources/reporter/database.go
- controllers/resources/reporter/helper.go
- controllers/resources/reporter/receiver.go
- controllers/resources/reporter/ui.go
- controllers/resources/service/containers.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/42708
> env variable into container from cr

- controllers/resources/reporter/helper.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46213
> update for reporter env var

- api/v1alpha1/ibmlicensing_types.go
- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_ibmlicensings.yaml
- config/crd/bases/operator.ibm.com_ibmlicensings.yaml
- config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46230
> spelling Red Hat

- Makefile
- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
fix replace tag
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46228
> fix replace

- docs/Content/Configuration.md
- docs/Content/Troubleshooting.md
- docs/License_Service_main.md
Troubleshooting updated with the following scenario: License Service API is unavailable with 503 Service Unavailable error
Using custom certificates procedure updated.
> Troubleshooting and custom certificate changes

- README.md
- docs/Content/Preparing_for_installation.md
- docs/Content/Retrieving_data.md
- docs/Content/Troubleshooting.md
- docs/License_Service_main.md
The following updates are made: 
IBM Cloud Platform Common Services -> IBM Cloud Pak foundational services
IBM Knowledge Center -> IBM Documentation
old KC links -> IBM Documentation links
> Bk 1.4 cs name change

- README.md
- docs/Content/Configuration.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_on_OCP.md
A note is changed to inform the user that this branch contains operator and docs for 1.5.x version.
> Bk doc updates 1.5

- docs/Content/Install_on_OCP.md
> minor doc fix

- Makefile
- bundle/manifests/ibm-license-service_v1_serviceaccount.yaml
- bundle/manifests/ibm-licensing-operator_v1_serviceaccount.yaml
- docs/Content/Install_offline.md
- docs/Content/Install_without_OLM.md
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47934
> Removed ServiceAccounts

- README.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_without_OLM.md
- docs/Content/Troubleshooting.md
- docs/License_Service_main.md
Hi @SzymonKowalczyk please review the changes to the 1.6 docs.
> update 1.6 docs

- README.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_without_OLM.md
- docs/Content/Troubleshooting.md
- docs/License_Service_main.md
@SzymonKowalczyk Could you please review? 
Changes in the PR: 
- I changed the versions to v1.7. 
- I updated the note in the readme
I do not think that we do need a note that the procedure is for a specific release. It is determined by the branch, and we have a note in readme. Your thoughts?
> 1.7 doc updates

- docs/Content/Preparing_for_installation.md
- docs/License_Service_main.md
@SzymonKowalczyk Could you please review the cluster permissions added to documentation? Thank you!
> add cluster permissions

- docs/Content/Install_from_scratch.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Preparing_for_installation.md
OCP support amended to say we support 4.6 and higher
> update OCP support

- docs/Content/Install_from_scratch.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Preparing_for_installation.md
Updated supported platforms: 
- Supported version of OCP : 4.6 and higher
- Kubernetes: 1.16
> update supported systems

- README.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Installation_scenarios.md
- docs/Content/Preparing_for_installation.md
- docs/License_Service_main.md
Updating versions for consistency, supported platforms and adding information about hyperthreading.
> Bk doc update 1.8

- docs/Content/Automatic_installation.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Installation_scenarios.md
@SzymonKowalczyk Hi Szymon, could you please review the note? Thanks!
> add note to indicate the doc is outdated

- docs/Content/Automatic_installation.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Installation_scenarios.md
@SzymonKowalczyk Hi Szymon, the PR that adds a note about outdated install procedures to 1.5 branch. Could you please review? Thanks!
> adding the note about outdated install procedure to 1.5 branch

- docs/Content/Automatic_installation.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Installation_scenarios.md
- docs/Content/Preparing_for_installation.md
- docs/License_Service_main.md
@SzymonKowalczyk Hi Szymon, adding the notes to 1.8 branch. Could you please review?
> update documentation with a note about outdated install procedures

- docs/Content/Automatic_installation.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Installation_scenarios.md
@SzymonKowalczyk Hi Szymon, addinga  note about the outdated install procedure for 1.6 branch. Could you please reveiw?
> update the note about outdated installation procedure

- docs/Content/Automatic_installation.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Installation_scenarios.md
@SzymonKowalczyk Hi Szymon! The oudtated note in install procedures for 1.4 branch. Please rveview, thanks!
> Bk doc outdated note 1.4

- docs/Content/Automatic_installation.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Installation_scenarios.md
@SzymonKowalczyk Hi Szymon adding the note about outdated installation procedures for 1.3 branch. Please review, thanks!
> add note about outdated installation procedures for 1.3 branch

- docs/Content/Preparing_for_installation.md
- docs/License_Service_main.md
@lukas Hi Szymon, I am fixing the hardware sizings
> update hardware requirements

- Makefile
- api/v1alpha1/features.go
- api/v1alpha1/ibmlicensing_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_ibmlicensings.yaml
- common/scripts/updateCSV/saCP2.yaml
- common/scripts/updateCSV/saP2.yaml
- common/scripts/updateCSV/updateCP2.yaml
- common/scripts/updateCSV/updateP2.yaml
- config/crd/bases/operator.ibm.com_ibmlicensings.yaml
- config/rbac/role_binding.yaml
- config/rbac/role_operands.yaml
- config/rbac/service_account.yaml
- controllers/resources/deployments.go
- controllers/resources/service/containers.go
- controllers/resources/service/deployments.go
- controllers/resources/service/helper.go
- docs/Content/Preparing_for_installation.md
with access to pods only in chosen namespaces for operand, and new flag for this option
> add new sa ibm-license-service-restricted 

- README.md
- docs/Content/Install_offline.md
- docs/Content/Install_on_OCP.md
- docs/Content/Installation_scenarios.md
- docs/Content/Preparing_for_installation.md
- docs/License_Service_main.md
> update offline instruction - lukaszG

- .github/workflows/kind.yml
- Makefile
- common/scripts/tests/.osdk-scorecard.yaml
- common/scripts/tests/tests.bats
- common/scripts/tests/tests_reporter.bats
- deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
- deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
- deploy/olm-catalog/ibm-licensing-operator/1.3.4/ibm-licensing-operator.v1.3.4.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-licensing-operator/1.3.4/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
- deploy/olm-catalog/ibm-licensing-operator/1.3.4/operator.ibm.com_ibmlicensings_crd.yaml
- deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
- deploy/operator.yaml
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_without_OLM.md
- docs/Content/Troubleshooting.md
- docs/Content/Uninstalling.md
- version/version.go
https://github.ibm.com/ibmprivatecloud/roadmap/issues/51350
> Update to 1.3.4

- api/v1alpha1/helper.go
- controllers/ibmlicensing_controller.go
Fixes feature status and adds small logging changes
> Fix feature status

- docs/Content/Configuration.md
- docs/Content/Preparing_for_installation.md
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51678
@SzymonKowalczyk Could you please review the changes? 
Thanks!
> Adding information about profiles to required resources page

- api/v1alpha1/helper.go
Update default LS resources to be consistent with CS x86 medium profile
> Update default resources to CS x86 medium profile

- README.md
- docs/Content/Automatic_installation.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_on_OCP.md
- docs/Content/Install_without_OLM.md
- docs/Content/Installation_scenarios.md
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51955
@SzymonKowalczyk Could you please review? Is that it?
Adding the notes about outdated install procedures.
> update notes in install procedure

- README.md
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51955
@SzymonKowalczyk Hi ! Could you please review? Adding a note to read me. Thanks!
> update a note in readme

- docs/Content/Backup_and_upgrade.md
and unnecessary line, allowing to copy commands
> improve docs by deleting spaces

- docs/Content/Backup_and_upgrade.md
> improve docs by deleting spaces and unnecessary line

- docs/Content/Automatic_installation.md
- docs/Content/Backup_and_upgrade.md
- docs/Content/Configuration.md
- docs/Content/Install_from_scratch.md
- docs/Content/Install_without_OLM.md
- docs/Content/Uninstalling.md
- docs/Content/Whats_new.md
This PR is a draft for review. It will be merged after code freeze. 
The following issues are addressed by these changes: 
- Upgrade: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53122
- Ingress examples: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53121
- Additional steps when install LS on IKS\EKS : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53100
- What's New added for 1.15
@geforcelive Let's discuss the changes
> documentation updates

- Makefile
- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
- config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
- config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
- docs/Content/Install_from_scratch.md
- docs/Content/Install_offline.md
- docs/Content/Install_without_OLM.md
- version/version.go
Reverts IBM/ibm-licensing-operator#611
> Revert "Update to 1.16 version"

- docs/Content/Automatic_installation.md
- docs/Content/Install_offline.md
- docs/Content/Install_without_OLM.md
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53543
> fixing the offline installation typo

- Makefile
- docs/Content/Configuration.md
- docs/Content/Preparing_for_installation.md
- docs/Content/Whats_new.md
- docs/License_Service_main.md
@adamdyszy @Lukasz-Gebarowski Can you please review the PR with the doc updates for Tanzu? 
Related to: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54227
> documentation updates for Tanzu

- Makefile
Signed-off-by: Jakub Solecki <Jakub.Solecki@ibm.com>
> enable internal ltsr catalog for devops

- common/scripts/ibm_licensing_operator_install.sh
Signed-off-by: adam <Adam.Dyszy@ibm.com>
> fix too fast sub recreation and wrong echo

- Makefile
Signed-off-by: Jakub Solecki <Jakub.Solecki@ibm.com>
> get current git branch name

- Makefile
Signed-off-by: Jakub Solecki <Jakub.Solecki@ibm.com>
> get current git branch name ltsr

- docs/Content/Configuration.md
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54460
> cherry-pick: configuration_update

- go.mod
- go.sum
Signed-off-by: Jakub Solecki <Jakub.Solecki@ibm.com>
> update go-restful to address CVE

- controllers/ibmlicensing_controller.go
not finding resource and kind of not wanted object no longer blocks reconcilation
> Fix reconcile when no service monitors - future

- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
Change default crd reconcile interval from 1h to 5m.
> Change default crd reconcile interval

- controllers/ibmlicensing_controller.go
- controllers/resources/service/routing.go
- go.mod
- go.sum
Refactor route creation logic, bump github.com/sirupsen/logrus to v1.9.3
> Fix routeEnabled functionality producing error

- .github/workflows/kind.yml
- Makefile
Add login to the artifactory in the `kind` workflow to prevent issues with revoked access token.
NaN
-
-
> Add explicit login to the artifactory

- .github/workflows/kind.yml
Add login to the artifactory in the `kind` workflow to prevent issues with revoked access token.
NaN
-
-
> Add explicit login to the artifactory step in kind workflow

- .github/workflows/kind.yml
- common/scripts/ibm_licensing_operator_install.sh
* CSV supported version update
* OLM version updated to v0.19.1
* bundle update
* olm version in kind test update
* Update kind.yml
* Update kind.yml 1.24.15
* Update kind
---------
> Olm version update to v0.19.1 (#824)

- api/v1/ibmlicensingdefinition_types.go
- api/v1/ibmlicensingquerysource_types.go
- api/v1alpha1/ibmlicensing_types.go
- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
- bundle/manifests/operator.ibm.com_ibmlicensingquerysources.yaml
- bundle/manifests/operator.ibm.com_ibmlicensings.yaml
- config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
- config/crd/bases/operator.ibm.com_ibmlicensingquerysources.yaml
- config/crd/bases/operator.ibm.com_ibmlicensings.yaml
- config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Update descriptions of `IBMLicensing`, `IBMLicensingDefinition` and `IBMLicensingQuerySource` to meet certification requirements.
> update remaining CRD descriptions

- Makefile
Use stable, existing images not development when testing catalogsource.
> Change operands used in catalog to integration

- controllers/resources/deployments.go
- controllers/resources/deployments_test.go
- testutils/mocks.go
Fixes the issue, where operator was endlessly overwriting Deployment due difference in Volumes in expected Deployment and one on the cluster.
> Change volumes comparison function to order-agnostic

- Makefile
- api/v1alpha1/helper.go
- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- controllers/resources/deployments.go
- controllers/resources/service/volumes.go
Reverts IBM/ibm-licensing-operator#855 - for some reason it causes nagative side effects https://github.ibm.com/IBMPrivateCloud/roadmap/issues/61003
> Revert "Add ephemeral storage request and emptyDir size limit"

- controllers/ibmlicensing_controller.go
- controllers/operandrequest_controller.go
- controllers/resources/deployments.go
- controllers/resources/helper.go
- controllers/resources/service/helper_test.go
- go.mod
Fixed bug with custom-added labels being removed on UpdateResources calls
> Fix labels auto removal

- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
> Add generated files for roles

- api/v1alpha1/ibmlicensing_types.go
- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- bundle/manifests/operator.ibm.com_ibmlicensings.yaml
- config/crd/bases/operator.ibm.com_ibmlicensings.yaml
- controllers/resources/service/containers.go
Enable Instana metrics collection support.
> implement Instana metrics collection integration

- bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
- config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
..as defined in https://docs.redhat.com/en/documentation/red_hat_software_certification/2024/html-single/red_hat_openshift_software_certification_policy_guide/index#con-operator-requirements_openshift-sw-cert-policy-products-managed and required by RH Certification
> ILS-390 Add required OLM operator bundle metadata

- .github/workflows/ci.yml
- .github/workflows/kind.yml
Remediate CVE-2025-22870 by upgrading golang to latest 1.23.X
<issue number>
-
-
> ILS-580 Remediate CVE 2025 22870

- Makefile
- common/makefile-generate/yaml-cr-spec-part
- common/makefile-generate/yaml-deployment-pull-secrets-part
Describe the big picture of your changes here. If it fixes a bug or resolves a feature request, be sure to link to that issue.
<issue number>
-
-
> Add changes for licensing deploy info

- deploy/yamls/license-service-reporter/install/install-license-service-reporter-no-olm-offline.yaml
- deploy/yamls/license-service-reporter/install/install-license-service-reporter-no-olm.yaml
Update yamls for the LSR install for no olm.
<issue number>
-
-
> Update no olm yamls

- Makefile
- common/makefile-generate/yaml-cr-spec-part
- deploy/argo-cd/README.md
- deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/cluster-rbac.yaml
- deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/crds.yaml
- deploy/argo-cd/components/license-service/helm-cluster-scoped/values.yaml
- deploy/argo-cd/components/license-service/helm/templates/cr.yaml
- deploy/argo-cd/components/license-service/helm/templates/deployment.yaml
- deploy/argo-cd/components/license-service/helm/templates/rbac.yaml
- deploy/argo-cd/components/license-service/helm/templates/serviceaccounts.yaml
- deploy/argo-cd/components/license-service/helm/values.yaml
- deploy/argo-cd/components/reporter/helm-cluster-scoped/templates/cluster-rbac.yaml
- deploy/argo-cd/components/reporter/helm-cluster-scoped/templates/crd.yaml
- deploy/argo-cd/components/reporter/helm-cluster-scoped/values.yaml
- deploy/argo-cd/components/reporter/helm/templates/cr.yaml
- deploy/argo-cd/components/reporter/helm/templates/deployment.yaml
- deploy/argo-cd/components/reporter/helm/templates/rbac.yaml
- deploy/argo-cd/components/reporter/helm/templates/serviceaccounts.yaml
- deploy/argo-cd/components/reporter/helm/values.yaml
- deploy/argo-cd/components/scanner/helm-cluster-scoped/templates/cluster-rbac.yaml
- deploy/argo-cd/components/scanner/helm-cluster-scoped/templates/crd.yaml
- deploy/argo-cd/components/scanner/helm-cluster-scoped/values.yaml
- deploy/argo-cd/components/scanner/helm/templates/cr.yaml
- deploy/argo-cd/components/scanner/helm/templates/deployment.yaml
- deploy/argo-cd/components/scanner/helm/templates/rbac-for-auto-connect.yaml
- deploy/argo-cd/components/scanner/helm/templates/rbac.yaml
- deploy/argo-cd/components/scanner/helm/templates/serviceaccounts.yaml
- deploy/argo-cd/components/scanner/helm/values.yaml
Describe the big picture of your changes here. If it fixes a bug or resolves a feature request, be sure to link to that issue.
-
-
> ILS-852 Adjust helm charts to comply with CPD tech spec

- Makefile
- deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/cluster-rbac-for-operandrequests.yaml
- deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/cluster-rbac.yaml
- deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/cr.yaml
- deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/crd.yaml
- deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/deployment.yaml
- deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/rbac.yaml
- deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/serviceaccounts.yaml
Describe the big picture of your changes here. If it fixes a bug or resolves a feature request, be sure to link to that issue.
<issue number>
-
-
> Fix helm labels

- README.md
Change only in the Readme.md file to indicate the badge earned. No testing needed.
no parent
- N/A
> Update README.md with OpenSSF practices badge
